import { Leva, useControls } from "leva";
import { useEffect } from "react";

export default function PatchSpiderControls({ initialValues, onChange }) {
  const {
    headScale,
    bodyScale,
    jawScale,
    headRot,
    bodyRot,
    jawRot,
    headOffsetX,
    headOffsetY,
    bodyOffsetX,
    bodyOffsetY,
    jawOffsetX,
    jawOffsetY,
    legScale,
    legRot1,
    legRot2,
    legRot3,
    legRot4,
    legOffsetX,
    legOffsetY,
    bodyGap,
    legAttach,
    jawLen,
    headGap,
    jawHeadGap,
    jawSpreadDeg,
    jawAnchorGap,
    jawAnchorHeadGap,
    legSwingAmpDeg,
    legSwingSpeed,
  } = useControls("Patch Spider", {
    headScale: { value: initialValues.headScale ?? 1.0, min: 0.05, max: 3, step: 0.01 },
    bodyScale: { value: initialValues.bodyScale ?? 1.0, min: 0.05, max: 3, step: 0.01 },
    jawScale: { value: initialValues.jawScale ?? 1.0, min: 0.05, max: 3, step: 0.01 },
    headRot: { value: initialValues.headRot ?? 90, min: -180, max: 180, step: 1 },
    bodyRot: { value: initialValues.bodyRot ?? 90, min: -180, max: 180, step: 1 },
    jawRot: { value: initialValues.jawRot ?? 90, min: -180, max: 180, step: 1 },
    headOffsetX: { value: initialValues.headOffsetX ?? 0, min: -200, max: 200, step: 1 },
    headOffsetY: { value: initialValues.headOffsetY ?? 0, min: -200, max: 200, step: 1 },
    bodyOffsetX: { value: initialValues.bodyOffsetX ?? 0, min: -200, max: 200, step: 1 },
    bodyOffsetY: { value: initialValues.bodyOffsetY ?? 0, min: -200, max: 200, step: 1 },
    jawOffsetX: { value: initialValues.jawOffsetX ?? 0, min: -200, max: 200, step: 1 },
    jawOffsetY: { value: initialValues.jawOffsetY ?? 0, min: -200, max: 200, step: 1 },
    legScale: { value: initialValues.legScale ?? 1.6, min: 0.05, max: 3, step: 0.01 },
    legRot1: { value: initialValues.legRot1 ?? 0, min: -180, max: 180, step: 1 },
    legRot2: { value: initialValues.legRot2 ?? 0, min: -180, max: 180, step: 1 },
    legRot3: { value: initialValues.legRot3 ?? 0, min: -180, max: 180, step: 1 },
    legRot4: { value: initialValues.legRot4 ?? 0, min: -180, max: 180, step: 1 },
    legOffsetX: { value: initialValues.legOffsetX ?? 0, min: -200, max: 200, step: 1 },
    legOffsetY: { value: initialValues.legOffsetY ?? 0, min: -200, max: 200, step: 1 },
    bodyGap: { value: initialValues.bodyGap ?? 57, min: -150, max: 300, step: 1 },
    legAttach: { value: initialValues.legAttach ?? 1.37, min: 0.2, max: 3.0, step: 0.01 },
    jawLen: { value: initialValues.jawLen ?? 200, min: 4, max: 400, step: 1 },
    headGap: { value: initialValues.headGap ?? 35, min: -100, max: 200, step: 1 },
    jawHeadGap: { value: initialValues.jawHeadGap ?? 74, min: -200, max: 200, step: 1 },
    jawSpreadDeg: { value: initialValues.jawSpreadDeg ?? 7, min: 0, max: 120, step: 1 },
    jawAnchorGap: { value: initialValues.jawAnchorGap ?? 71, min: 0, max: 200, step: 1 },
    jawAnchorHeadGap: { value: initialValues.jawAnchorHeadGap ?? 0, min: -200, max: 200, step: 1 },
    legSwingAmpDeg: { value: initialValues.legSwingAmpDeg ?? 14, min: 0, max: 60, step: 0.5 },
    legSwingSpeed: { value: initialValues.legSwingSpeed ?? 0.004, min: 0, max: 0.02, step: 0.0005 },
  });

  useEffect(() => {
    onChange?.({
      headScale,
      bodyScale,
      jawScale,
      headRot,
      bodyRot,
      jawRot,
      headOffset: { x: headOffsetX, y: headOffsetY },
      bodyOffset: { x: bodyOffsetX, y: bodyOffsetY },
      jawOffset: { x: jawOffsetX, y: jawOffsetY },
      legScale,
      legRots: { 1: legRot1, 2: legRot2, 3: legRot3, 4: legRot4 },
      legOffset: { x: legOffsetX, y: legOffsetY },
      bodyGap,
      legAttach,
      jawLen,
      headGap,
      jawHeadGap,
      jawSpreadDeg,
      jawAnchorGap,
      jawAnchorHeadGap,
      legSwingAmpDeg,
      legSwingSpeed,
    });
  }, [
    headScale,
    bodyScale,
    jawScale,
    headRot,
    bodyRot,
    jawRot,
    headOffsetX,
    headOffsetY,
    bodyOffsetX,
    bodyOffsetY,
    jawOffsetX,
    jawOffsetY,
    legScale,
    legRot1,
    legRot2,
    legRot3,
    legRot4,
    legOffsetX,
    legOffsetY,
    bodyGap,
    legAttach,
    jawLen,
    headGap,
    jawHeadGap,
    jawSpreadDeg,
    jawAnchorGap,
    jawAnchorHeadGap,
    legSwingAmpDeg,
    legSwingSpeed,
  ]);

  // 패널이 접혀 보이지 않는 문제 방지: 펼친 상태 + 한 줄 라벨
  return <Leva collapsed={false} oneLineLabels />;
}

